services:
  postgres:
    image: postgres:16-alpine
    container_name: obsidianragengine-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ObsidianNotes
    ports:
      - "6201:5432"
    volumes:
      - obsidianragengine-postgres-data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant:latest
    container_name: obsidianragengine-qdrant
    restart: unless-stopped
    ports:
      - "6202:6333"     # http://localhost:6202/dashboard
      - "6203:6334"     # grpc
    volumes:
      - obsidianragengine-qdrant-data:/qdrant/storage

  tesseract:
    image: hertzg/tesseract-server:latest
    container_name: obsidianragengine-tesseract
    restart: unless-stopped
    ports:
      - "6301:8884"

  ollama:
    image: ollama/ollama:latest
    container_name: obsidianragengine-ollama
    restart: unless-stopped
    ports:
      - "6302:11434"
    volumes:
      - obsidianragengine-ollama-data:/root/.ollama
    entrypoint: ["/bin/sh", "-c", "(until ollama list > /dev/null 2>&1; do echo 'Waiting for Ollama...'; sleep 1; done && ollama pull nomic-embed-text) & ollama serve"]

volumes:
  obsidianragengine-postgres-data:
  obsidianragengine-qdrant-data:
  obsidianragengine-ollama-data:
